using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SDK.Enum
{
    /// <summary>
    /// 无用类，API JSON 参考说明
    /// </summary>
    public enum APIJsonEnum
    {
        [Description("输出日志")]
        apijson0,
        [Description("发送好友消息")]
        apijson1,
        [Description("发送群消息")]
        apijson2,
        [Description("发送群临时消息")]
        apijson3,
        [Description("添加好友")]
        apijson4,
        [Description("添加群")]
        apijson5,
        [Description("删除好友")]
        apijson6,
        [Description("置屏蔽好友")]
        apijson7,
        [Description("置特别关心好友")]
        apijson8,
        [Description("发送好友json消息")]
        apijson9,
        [Description("发送群json消息")]
        apijson10,
        [Description("上传好友图片")]
        apijson11,
        [Description("上传群图片")]
        apijson12,
        [Description("上传好友语音")]
        apijson13,
        [Description("上传群语音")]
        apijson14,
        [Description("上传头像")]
        apijson15,
        [Description("设置群名片")]
        apijson16,
        [Description("取昵称_从缓存")]
        apijson17,
        [Description("强制取昵称")]
        apijson18,
        [Description("获取skey")]
        apijson19,
        [Description("获取pskey")]
        apijson20,
        [Description("获取clientkey")]
        apijson21,
        [Description("取框架QQ")]
        apijson22,
        [Description("取好友列表")]
        apijson23,
        [Description("取群列表")]
        apijson24,
        [Description("取群成员列表")]
        apijson25,
        [Description("设置管理员")]
        apijson26,
        [Description("取管理层列表")]
        apijson27,
        [Description("取群名片")]
        apijson28,
        [Description("取个性签名")]
        apijson29,
        [Description("修改昵称")]
        apijson30,
        [Description("修改个性签名")]
        apijson31,
        [Description("删除群成员")]
        apijson32,
        [Description("禁言群成员")]
        apijson33,
        [Description("退群")]
        apijson34,
        [Description("解散群")]
        apijson35,
        [Description("上传群头像")]
        apijson36,
        [Description("全员禁言")]
        apijson37,
        [Description("群权限_发起新的群聊")]
        apijson38,
        [Description("群权限_发起临时会话")]
        apijson39,
        [Description("群权限_上传文件")]
        apijson40,
        [Description("群权限_上传相册")]
        apijson41,
        [Description("群权限_邀请好友加群")]
        apijson42,
        [Description("群权限_匿名聊天")]
        apijson43,
        [Description("群权限_坦白说")]
        apijson44,
        [Description("群权限_新成员查看历史消息")]
        apijson45,
        [Description("群权限_邀请方式设置")]
        apijson46,
        [Description("撤回消息_群聊")]
        apijson47,
        [Description("撤回消息_私聊本身")]
        apijson48,
        [Description("设置位置共享")]
        apijson49,
        [Description("上报当前位置")]
        apijson50,
        [Description("是否被禁言")]
        apijson51,
        [Description("处理群验证事件")]
        apijson52,
        [Description("处理好友验证事件")]
        apijson53,
        [Description("查看转发聊天记录内容")]
        apijson54,
        [Description("上传群文件")]
        apijson55,
        [Description("创建群文件夹")]
        apijson56,
        [Description("设置在线状态")]
        apijson57,
        [Description("api是否有权限")]
        apijson58,
        [Description("重载自身")]
        apijson59,
        [Description("取插件数据目录")]
        apijson60,
        [Description("QQ点赞")]
        apijson61,
        [Description("取图片下载地址")]
        apijson62,
        [Description("查询好友信息")]
        apijson63,
        [Description("查询群信息")]
        apijson64,
        [Description("框架重启")]
        apijson65,
        [Description("群文件转发至群")]
        apijson66,
        [Description("群文件转发至好友")]
        apijson67,
        [Description("好友文件转发至好友")]
        apijson68,
        [Description("置群消息接收")]
        apijson69,
        [Description("取群名称_从缓存")]
        apijson70,
        [Description("发送免费礼物")]
        apijson71,
        [Description("取好友在线状态")]
        apijson72,
        [Description("取QQ钱包个人信息")]
        apijson73,
        [Description("获取订单详情")]
        apijson74,
        [Description("提交支付验证码")]
        apijson75,
        [Description("分享音乐")]
        apijson76,
        [Description("更改群聊消息内容")]
        apijson77,
        [Description("更改私聊消息内容")]
        apijson78,
        [Description("群聊口令红包")]
        apijson79,
        [Description("群聊拼手气红包")]
        apijson80,
        [Description("群聊普通红包")]
        apijson81,
        [Description("群聊画图红包")]
        apijson82,
        [Description("群聊语音红包")]
        apijson83,
        [Description("群聊接龙红包")]
        apijson84,
        [Description("群聊专属红包")]
        apijson85,
        [Description("好友口令红包")]
        apijson86,
        [Description("好友普通红包")]
        apijson87,
        [Description("好友画图红包")]
        apijson88,
        [Description("好友语音红包")]
        apijson89,
        [Description("好友接龙红包")]
        apijson90,
        [Description("重命名群文件夹")]
        apijson91,
        [Description("删除群文件夹")]
        apijson92,
        [Description("删除群文件")]
        apijson93,
        [Description("保存文件到微云")]
        apijson94,
        [Description("移动群文件")]
        apijson95,
        [Description("取群文件列表")]
        apijson96,

    }
}
